INTERNAL_TO_DECISION = {
    "COST_WARN_INCREASE": "COST_INCREASE_WARN",
    "COST_BLOCK_INCREASE": "COST_INCREASE_BLOCK",
    "LATENCY_WARN_INCREASE": "LATENCY_INCREASE_WARN",
    "LATENCY_BLOCK_INCREASE": "LATENCY_INCREASE_BLOCK",
    "PII_BLOCK_EMAIL": "PII_EMAIL_BLOCK",
    "PII_BLOCK_PHONE": "PII_PHONE_BLOCK",
    "PII_BLOCK_CREDIT_CARD": "PII_CREDIT_CARD_BLOCK",
    "PII_BLOCK_SSN": "PII_SSN_BLOCK",
    "DRIFT_BLOCK_EMPTY": "DRIFT_EMPTY_OUTPUT_WARN",
    "DRIFT_WARN_SHORT_OUTPUT": "DRIFT_TOO_SHORT_WARN",
    "DRIFT_WARN_LENGTH_DELTA": "DRIFT_LENGTH_WARN",
    "DRIFT_WARN_LOW_SIMILARITY": "DRIFT_SIMILARITY_WARN",
    "STRICT_PROMOTED_WARN": "STRICT_MODE_PROMOTION_BLOCK",
}

DECISION_TO_INTERNAL = {v: k for k, v in INTERNAL_TO_DECISION.items()}
